#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  ca.project.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.project.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.supplychainorg.project.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/70a7b4ddda0a9f9e29bd3a62dc873cf943b18da90d7a6cdbd77b01bfcbad37e4_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/supplychainorg.project.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca
    networks:
      - basic

  orderer.project.com:
    container_name: orderer.project.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      #- ORDERER_GENERAL_TLS_ENABLED=true
      #- ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      #- ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      #- ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerSupplychainOrg/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/project.com/orderers/orderer.project.com/:/etc/hyperledger/crypto/orderer
        - ./crypto-config/peerOrganizations/supplychainorg.project.com/peers/administrator.supplychainorg.project.com/:/etc/hyperledger/crypto/peerSupplychainOrg
    networks:
      - basic

  administrator.supplychainorg.project.com:
    container_name: administrator
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=administrator.supplychainorg.project.com
      - CORE_PEER_LOCALMSPID=SupplychainMSP
      - CORE_PEER_ADDRESS=administrator.supplychainorg.project.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=[supplier.supplychainorg.project.com:7051,distributer1.supplychainorg.project.com:7051,distributer2.supplychainorg.project.com:7051]
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=administrator.supplychainorg.project.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./crypto-config/peerOrganizations/supplychainorg.project.com/peers/administrator.supplychainorg.project.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/supplychainorg.project.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.project.com
      - couchdb
    networks:
      - basic

  supplier.supplychainorg.project.com:
    container_name: supplier
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=supplier.supplychainorg.project.com
      - CORE_PEER_LOCALMSPID=SupplychainMSP
      - CORE_PEER_ADDRESS=supplier.supplychainorg.project.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=administrator.supplychainorg.project.com:7051
      # CORE_PEER_GOSSIP_EXTERNALENDPOINT If this is not set, then the endpoint information about the peer will not be broadcast
      # to peers in other organizations, and in fact - that peer will only be known to its own organization.
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=supplier.supplychainorg.project.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ./crypto-config/peerOrganizations/supplychainorg.project.com/peers/supplier.supplychainorg.project.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/supplychainorg.project.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.project.com
      - couchdb
    networks:
      - basic

  distributer1.supplychainorg.project.com:
    container_name: distributer1
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=distributer1.supplychainorg.project.com
      - CORE_PEER_LOCALMSPID=SupplychainMSP
      - CORE_PEER_ADDRESS=distributer1.supplychainorg.project.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=[administrator.supplychainorg.project.com:7051,supplier.supplychainorg.project.com:7051,distributer2.supplychainorg.project.com:7051]
      - CORE_PEER_GOSSIP_BOOTSTRAP=administrator.supplychainorg.project.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=distributer1.supplychainorg.project.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ./crypto-config/peerOrganizations/supplychainorg.project.com/peers/distributer1.supplychainorg.project.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/supplychainorg.project.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.project.com
      - couchdb
    networks:
      - basic

  distributer2.supplychainorg.project.com:
    container_name: distributer2
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=distributer2.supplychainorg.project.com
      - CORE_PEER_LOCALMSPID=SupplychainMSP
      - CORE_PEER_ADDRESS=distributer2.supplychainorg.project.com:7051
      # - CORE_PEER_GOSSIP_BOOTSTRAP=[administrator.supplychainorg.project.com:7051,supplier.supplychainorg.project.com:7051,distributer2.supplychainorg.project.com:7051]
      - CORE_PEER_GOSSIP_BOOTSTRAP=administrator.supplychainorg.project.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=distributer2.supplychainorg.project.com:7051
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - ./crypto-config/peerOrganizations/supplychainorg.project.com/peers/distributer2.supplychainorg.project.com/:/etc/hyperledger/crypto/peer
        - ./crypto-config/peerOrganizations/supplychainorg.project.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.project.com
      - couchdb
    networks:
      - basic

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_LOCALMSPID=SupplychainMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/supplychainorg.project.com/users/Admin@supplychainorg.project.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
        - basic
